---
abstract: 'Make your text awesome!'
author:
  - 'Marcus Smith <carwash@cpan.org>'
build_requires:
  English: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-AwesomeQuotes
requires:
  Carp: 0
  Exporter: 0
  Unicode::Normalize: 0
  utf8: 0
version: 0.0.1
